#!/usr/bin/bash
FILE=$1
while read -r NUMBERS;
do
	echo "Processing $NUMBER"
	i=2
	while [ $i -le $((NUMBER/2)) ]; do
		if [ $((NUMBER % i)) -eq 0 ]; then
			echo "$NUMBER=$(($NUMBER/$i))*$i"
			break
		fi
		((i++))
	done
done < "$FILE"
